" НАСТРОЙКА ТАБОВ И ОТСТУПОВ
set tabstop=3                   " Ширина тубуляции
set shiftwidth=3                " Ширина отступов для операторов >> и <<. (это когда в командном режиме нажимаем два раза ">" (т.е. получается что ">>")).
set expandtab                   " Заменяем tab`ы пробелами
set smarttab
set softtabstop=3               " 3 пробела в табе

" ПОДСВЕТКА СИНТАКСИСА
syntax on

" АВТОМАТИЧЕСКИЕ ОТСТУПЫ
set autoindent                  " Копирует отступы с текущей строки на новую
set smartindent                 " Добавляет дополнительные отступы для блоков кода (например после "{" в Си)
set cindent                     " Включаем умные отступы для Си

" НУМЕРАЦИЯ СТРОК
set nu                          " Включаем нумерацию строк

" ОТКЛЮЧЕНИЕ ПОДСВЕТКИ ПОИСКА    
set nohlsearch

" Установить плагин tpope/vim-sensible:
" 1)  mkdir -p ~/.vim/pack/tpope/start    2)    cd ~/.vim/pack/tpope/start  3) git clone https://tpope.io/vim/sensible.git
